version: '2.1'
services:
  fusion-server:
    build: .
    command: yarn start --environment=development
    expose:
      - 3000
    ports:
      - '3000:3000'
    network_mode: host
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -H "Accept: text/html" -f http://localhost:3000 || exit 1'
      interval: 5s
      timeout: 10s
      retries: 5
  chrome-standalone:
    image: >-
      selenium/standalone-chrome:latest@sha256:05fb982f176c8c836b188f85557e3c7ea6f291911c394200643862ef9b266155
    network_mode: host
    restart: always
    ports:
      - '4444:4444'
  firefox-standalone:
    image: >-
      selenium/standalone-firefox:latest@sha256:ee0abb000eb116e1ed3299ad887390539835887369cc2caf52889806315856cb
    network_mode: host
    restart: always
    ports:
      - '4444:4444'
  sauce-tunnel:
    image: >-
      henrrich/docker-sauce-connect:latest@sha256:9921657d1a3db8832f868ab25491363756abae52025a8d5af888aadc42ed31e9
    restart: always
    expose:
      - 4445
    ports:
      - 4445
    network_mode: host
    command:
      - '-u'
      - '${SAUCE_USERNAME}'
      - '-k'
      - '${SAUCE_ACCESS_KEY}'
      - '-i'
      - '${BUILDKITE_BUILD_NUMBER}'
      - '-p'
    environment:
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BUILDKITE_BUILD_NUMBER
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          grep -R "Sauce Connect is up" /tmp/sc-${BUILDKITE_BUILD_NUMBER}.log ||
          exit 1
      interval: 5s
      timeout: 5m
      retries: 10
  sauce-tunnel-healthy:
    build: .
    network_mode: host
    depends_on:
      sauce-tunnel:
        condition: service_healthy
  fusion-server-healthy:
    build: .
    network_mode: host
    depends_on:
      fusion-server:
        condition: service_healthy
  browser-tests:
    build: .
    network_mode: host
    depends_on:
      - sauce-tunnel-healthy
      - fusion-server-healthy
    environment:
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BUILDKITE_BUILD_NUMBER
  browser-tests-linters:
    build: .
    environment:
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BUILDKITE_BUILD_NUMBER
  browser-test-chrome:
    build: .
    network_mode: host
    depends_on:
      - chrome-standalone
      - fusion-server-healthy
    command: ./test-standalone.sh
  browser-test-firefox:
    build: .
    network_mode: host
    depends_on:
      - firefox-standalone
      - fusion-server-healthy
    command: ./test-standalone.sh
  fusion-server-node-last:
    extends: fusion-server
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  chrome-standalone-node-last:
    extends: chrome-standalone
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  firefox-standalone-node-last:
    extends: firefox-standalone
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  sauce-tunnel-node-last:
    extends: sauce-tunnel
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  sauce-tunnel-healthy-node-last:
    extends: sauce-tunnel-healthy
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  fusion-server-healthy-node-last:
    extends: fusion-server-healthy
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  browser-tests-node-last:
    extends: browser-tests
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  browser-tests-linters-node-last:
    extends: browser-tests-linters
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  browser-test-chrome-node-last:
    extends: browser-test-chrome
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
  browser-test-firefox-node-last:
    extends: browser-test-firefox
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
